### PR TITLE
Added Heart of Azeroth

### PR DESCRIPTION
**Pull request by dioxina**
This would add the Artifact Heart of Azeroth

### CODE REVIEW

**Comment by Meivyn** [comment]
You should fix your indentation, and some things aren't required in your code:

```LUA
if slotId == 2
local _, link, _, _, _, _, _, _, _, texture = GetItemInfo(NeckItemId)
```
Like this you don't retrieve data you don't want from ``GetItemInfo()``. Also brackets aren't needed.
I planned to add it today, so thanks I don't have to do it anymore.

**Comment by Meivyn** [comment]
You don't need the last ``_`` :)

```LUA
    ----------------------Artifact Neck------------------------------------
    if slotId == 2 and self:GetSelected(self.RAIDTIER) >= 80000 and self:GetSelected(self.RAIDTIER) < 90000 then
		  icon:SetUserData("disabled", true)
		  button:SetDisabled(true)
		  NeckItemId = 158075
		  local _, link, _, _, _, _, _, _, _, texture = GetItemInfo(NeckItemId)
		  icon:SetImage(texture)
		  icon:SetUserData("itemid", NeckItemId)
		  icon:SetUserData("itemlink", link)
		  label:SetText(link)
		  isLegionWeapon = true
    elseif (slotId == 16 or slotId == 17) and (self:GetSelected(self.RAIDTIER) >= 70000 and self:GetSelected(self.RAIDTIER) < 80000) then
    ----------------------Artifact weapons------------------------------------
```
Not sure why you does `` < 79999`` since you do ``>= 80000`` just before.

**Comment by zoveus** [comment]
thank you guys, i'll add your stuff to the addon soon as i can.

**Comment by Meivyn** [comment]
Don't merge our requests as they will conflict. Edit files yourself.

**Comment by zoveus** [comment]
okay, thank you for the hint.

**Pull request closed without merging**
