### PR TITLE
Wrong NPCIDs, Missing Alliance Boss, World Boss Loot

### PR DESCRIPTION
**Pull request by dioxina**
Uldir.lua
Fix the Wrong NPCIDs
Added World Boss Loot to Uldir
Raid Tier Version changed to higher than Dungeons, as the BiS window always jumps to the highest version when loading an expansion.

BestInSlotRedux_BfaDungeons.lua:
Added Missing Alliance Boss in Siege of Boralus

ZoneDetection:
Added BfA Mythic Dungeon difficulty for Boss Tooltips

Manager.lua:
Added Heart of Azeroth

BestInSlotRedux_LegionDungeons.lua / All Legion Raids.lua
Fix MAP for BfA

CustomItems.lua
Fix minimumIlvl for BfA

### CODE REVIEW

**Comment by zoveus** [comment]
How did you get all the npcIDs ? I want to update the extract script.

**Comment by dioxina** [comment]
With an ingame Macro + Boss @ target.

/run guid = UnitGUID("target"); local _, _, _,_,_, npc_id = strsplit("-",guid); print(npc_id)

**Comment by Meivyn** [comment]
There is no way to retrieve them with Encounter Journal as far as I know, and you can't use a target macro since the raid isn't accessible yet, so he probably retrieved them from Wowhead.

ZoneDetection retrieves them with this:
```LUA
  local _, unit = tooltip:GetUnit()
  if not unit then return end
  local guid = UnitGUID(unit)
  local npcType,_,_,_,_,npcId = strsplit("-", guid)
  if npcType and (npcType == "Creature" or npcType == "Vehicle") then
    npcId = tonumber(npcId)
```
It does it whenever you put your mouse hover a NPC. ``if not unit then return end`` prevents an error if you mouseover something that isn't a NPC, like an item.

``ExportRaid.lua`` uses EJ data to retrieve loots, so you can't really do the same for the ZoneDetection module.

The IDs you used are Encounter IDs, which aren't the same as NPC IDs. Encounters are used only by the Encounter Journal.

**Comment by dioxina** [comment]
Oh, I forgot. Meivyn told you the second source I forgot. I had to get the IDs from Raid via wowhead.

**Comment by zoveus** [comment]
Okay. Then I didn't miss anything. Thanks.

**Comment by anhility** [comment]
Please make pull requests into the dev branch in the future.

**Pull request closed without merging**
